Cosmetic changes to linux installer, added Java version check

diff --git a/qz-print/ant/linux/linux-installer.sh.in b/qz-print/ant/linux/linux-installer.sh.in
--- a/qz-print/ant/linux/linux-installer.sh.in
+++ b/qz-print/ant/linux/linux-installer.sh.in
@@ -17,21 +17,56 @@ destdir="${linux.installdir}"
 shortcut="$HOME/Desktop/${socket.name}.desktop"
 jarfile="${destdir}/${build.socket.name}.jar"
 
-echo
-echo "============================================"
-echo "            Installing ${socket.name}"
-echo "============================================"
-echo
-echo " - Stopping any running versions..."
+# OK dialog
+height=8; width=41
+function confirm_dialog() {
+   dialog --title "Install ${socket.name}" --backtitle "Install ${socket.name}" --yesno "$1" $height $width
+   if [ $? -ne 0 ]; then
+      echo -e "\n\n${bash.aborted}\n"
+      exit 1
+   fi
+}
+
+# Progress dialog
+function progress_dialog() {
+   echo "$1" | dialog --title "Install ${socket.name}" \
+    --backtitle "Install ${socket.name}" \
+    --gauge "$2" $height $width
+}
+
+function check_java() {
+   curver=$(java -version 2>&1 | grep -i version | cut -d'"' -f2 | cut -d'.' -f1-2) 
+   minver="${javac.target}"
+
+   if [ -z "$curver" ]; then
+      curver="0.0"
+   fi
+
+   if [ $(echo "$curver>=$minver" | bc -l) -eq 0 ]; then
+      echo -e "\n\n${bash.failure}\n"
+      echo "Please install Java ${javac.target} or higher to continue\n"
+   fi
+}
+
+confirm_dialog "Are you sure you want to install ${socket.name}?"
+
+progress_dialog 5 "Checking for Java ${javac.target}+..."
+check_java
+
+progress_dialog 10 "Stopping any running versions..."
 pkill -f "java -jar ${jarfile}"
-echo " - Removing old versions..."
+
+progress_dialog 20 "Stopping any running versions..."
 rm -rf "${destdir}" > /dev/null 2>&1
-echo " - Creating directory..."
+
+progress_dialog 25 "Creating directory..."
 mkdir -p "${destdir}" > /dev/null 2>&1
-echo " - Installing new version..."
+
+progress_dialog 30 "Installing new version..."
 cp -R ./ "${destdir}"
 rm "${destdir}/`basename $0`"
-echo " - Creating desktop shortcut..."
+
+progress_dialog 40 "Creating desktop shortcut..."
 echo "[Desktop Entry]
 Type=Application
 Name=${socket.name}
@@ -43,18 +78,18 @@ Comment=${socket.name}" > "${shortcut}"
 chmod +x "${shortcut}"
 
 # Ubuntu process restarter
-function restart_it {
+function restart_it() {
     # Check for running process, kill it
     ps -e |grep -q $1
     if [ $? -eq 0 ]; then
-        echo "   - Killing $1..."
+        progress_dialog $2 "Killing $1..."
         killall -w $1 > /dev/null 2>&1
     fi
 
     # Make sure process isn't running, start it
     ps -e |grep -q $1
     if [ $? -ne 0 ]; then
-        echo "   - Starting $1..."
+        progress_dialog $(($2 + 5)) "Starting $1..."
         nohup $1 > /dev/null 2>&1 &
     fi
 }
@@ -64,20 +99,16 @@ grep -q "Ubuntu" /etc/lsb-release
 if [ $? -eq 0 ]; then
     echo " - Ubuntu detected.  Restarting Unity Panel..."
     gsettings set com.canonical.Unity.Panel systray-whitelist "['all']" > /dev/null 2>&1
-    restart_it unity-panel-service
-    restart_it unity-2d-panel
+    restart_it unity-panel-service 50
+    restart_it unity-2d-panel 60
 fi
 
-echo " - Generating certificate..."
+progress_dialog 70 "Generating certificate..."
 chmod +x "${linux.keygen.out}"  > /dev/null 2>&1
 "${linux.keygen.out}"
 
 cd "${destdir}"
-echo " - Installation complete... Starting ${socket.name}..."
+progress_dialog 90 "Installation complete... Starting ${socket.name}..."
 nohup "java" -jar "${jarfile}" > /dev/null 2>&1 &
-echo
-echo "============================================"
-echo "                 Finished                   "
-echo "============================================"
-echo
+progress_dialog 100 "Finished.  QZ Tray should start automatically."
 exit 0
